{{- if (not (empty .Values.trow.proxyConfig.config)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trow.fullname" . }}-proxy-cfg
  labels:
    {{- include "trow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  proxy-registries.yaml: {{ .Values.trow.proxyConfig.config | toYaml | b64enc }}
{{- end }}
