---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "trow.fullname" . }}
  labels:
    {{- include "trow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trow.selectorLabels" . | nindent 6 }}
  serviceName: trow
  template:
    metadata:
      labels:
        {{- include "trow.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or .Values.trow.validation.enableWebhook .Values.trow.proxyConfig.enableWebhook }}
      initContainers:
      # TODO: remove this thing :'c
      - name: trow-webhook-cert-translate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            cp /etc/trow/webhook-cert-ecc/cert /etc/trow/webhook-cert && \
            openssl pkcs8 -topk8 -nocrypt -in /etc/trow/webhook-cert-ecc/key -out /etc/trow/webhook-cert/key
        volumeMounts:
        - name: webhook-cert-translated
          mountPath: /etc/trow/webhook-cert
        - name: webhook-cert-ecc
          mountPath: /etc/trow/webhook-cert-ecc
          readOnly: true
    {{- end }}
      containers:
      - name: trow
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--no-tls"
          - "-n"
          - {{ .Values.trow.domain | quote }}
          {{- if .Values.trow.host }}
          - "--host"
          - {{ .Values.trow.host | quote }}
          {{- end}}
          {{- if and (.Values.trow.user) (.Values.trow.password) }}
          - "-u"
          - {{ .Values.trow.user | quote }}
          - "--password-file"
          - "/etc/trow/pass"
          {{- end }}
          {{- if (not (empty .Values.trow.proxyConfig.config)) }}
          - "--proxy-registry-config-file=/etc/trow/proxy-registries.yaml"
          {{- end }}
          {{- if (not (empty .Values.trow.validation.config)) }}
          - "--image-validation-config-file=/etc/trow/validation.yaml"
          {{- end }}
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: data-vol
          mountPath: /data
      {{- if and (.Values.trow.user) (.Values.trow.password) }}
        - name: trow-pass
          mountPath: /etc/trow/pass
          subPath: pass
          readOnly: true
      {{- end}}
      {{- if (not (empty .Values.trow.proxyConfig.config)) }}
        - name: trow-proxy-cfg
          mountPath: /etc/trow/proxy-registries.yaml
          subPath: proxy-registries.yaml
          readOnly: true
      {{- end}}
      {{- if (not (empty .Values.trow.validation.config)) }}
        - name: trow-validation-cfg
          mountPath: /etc/trow/validation.yaml
          subPath: validation.yaml
          readOnly: true
      {{- end}}
      {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- if or .Values.trow.validation.enableWebhook .Values.trow.proxyConfig.enableWebhook }}
      - name: trow-webhook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--cert=/etc/trow/webhook-cert/cert"
          - "--key=/etc/trow/webhook-cert/key"
          - "-n"
          - {{ .Values.trow.domain | quote }}
          {{- if and (.Values.trow.user) (.Values.trow.password) }}
          - "-u"
          - {{ .Values.trow.user | quote }}
          - "--password-file=/etc/trow/pass"
          {{- end }}
          {{- if (not (empty .Values.trow.proxyConfig.config)) }}
          - "--proxy-registry-config-file=/etc/trow/proxy-registries.yaml"
          {{- end }}
          {{- if (not (empty .Values.trow.validation.config)) }}
          - "--image-validation-config-file=/etc/trow/validation.yaml"
          {{- end }}
        ports:
        - name: webhook
          containerPort: 8443
        volumeMounts:
        - name: data-vol
          mountPath: /data
        - name: webhook-cert-translated
          mountPath: /etc/trow/webhook-cert
          readOnly: true
      {{- if and (.Values.trow.user) (.Values.trow.password) }}
        - name: trow-pass
          mountPath: /etc/trow/pass
          subPath: pass
          readOnly: true
      {{- end}}
      {{- if (not (empty .Values.trow.proxyConfig.config)) }}
        - name: trow-proxy-cfg
          mountPath: /etc/trow/proxy-registries.yaml
          subPath: proxy-registries.yaml
          readOnly: true
      {{- end}}
      {{- if (not (empty .Values.trow.validation.config)) }}
        - name: trow-validation-cfg
          mountPath: /etc/trow/validation.yaml
          subPath: validation.yaml
          readOnly: true
      {{- end}}
      {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
      {{- end }}

    {{- end }}
      volumes:
      {{- if or .Values.trow.validation.enableWebhook .Values.trow.proxyConfig.enableWebhook }}
        - name: webhook-cert-ecc
          secret:
            secretName: {{ include "trow.fullname" . }}-admission
        - name: webhook-cert-translated
          emptyDir: {}
      {{- end }}
      {{- if and (.Values.trow.user) (.Values.trow.password) }}
        - name: trow-pass
          secret:
            secretName: {{ include "trow.fullname" . }}-password
      {{- end}}
      {{- if (not (empty .Values.trow.proxyConfig.config)) }}
        - name: trow-proxy-cfg
          secret:
            secretName: {{ include "trow.fullname" . }}-proxy-cfg
      {{- end }}
      {{- if (not (empty .Values.trow.validation.config)) }}
        - name: trow-validation-cfg
          configMap:
            name: {{ include "trow.fullname" . }}-validation-cfg
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.volumeClaim }}
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        {{- toYaml . | nindent 8 }}
  {{- end }}
