{{- if or .Values.trow.validation.enableWebhook .Values.trow.proxyConfig.enableWebhook -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trow.fullname" . }}-admission-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "trow.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
spec:
{{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  ttlSecondsAfterFinished: 0
{{- end }}
  template:
    metadata:
      name: {{ include "trow.fullname" . }}-admission-patch
      labels:
        {{- include "trow.labels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook
    spec:
      containers:
      {{- if .Values.trow.validation.enableWebhook }}
        - name: patch-validation
          image: {{ .Values.webhookPatch.image.image }}
          imagePullPolicy: {{ .Values.webhookPatch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ include "trow.fullname" . }}-validation
            - --namespace=$(POD_NAMESPACE)
            - --patch-mutating=false
            - --secret-name={{ include "trow.fullname" . }}-admission
            - --patch-failure-policy={{ .Values.trow.validation.onWebhookFailure }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
      {{- end }}
      {{- if .Values.trow.proxyConfig.enableWebhook }}
        - name: patch-mutation
          image: {{ .Values.webhookPatch.image.image }}
          imagePullPolicy: {{ .Values.webhookPatch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ include "trow.fullname" . }}-mutation
            - --namespace=$(POD_NAMESPACE)
            - --patch-validating=false
            - --secret-name={{ include "trow.fullname" . }}-admission
            - --patch-failure-policy={{ .Values.trow.proxyConfig.onWebhookFailure }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "trow.fullname" . }}-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        fsGroup: 2000
{{- end }}
