{{- if or .Values.trow.validation.enableWebhook .Values.trow.proxyConfig.enableWebhook -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ include "trow.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "trow.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
{{- end }}
