# Also builds the Docker images, but we want this name on the badge
name: OCI Conformance

on:
  push:
    branches:
      - main

jobs:
  upload_images:
    outputs:
      container-image: ${{ steps.build-images.outputs.container-image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - uses: sigstore/cosign-installer@main
      - name: Build and push multi-arch image
        id: build-images
        run: ./docker/multi-arch.sh
        env:
          COSIGN_EXPERIMENTAL: 1

  helm_chart_validation:
    runs-on: ubuntu-latest
    needs: upload_images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0
        with:
          config: .github/workflows/config/kind.yaml
      - name: Install Ingress
        run: |
          .github/workflows/config/install-kind-ingress.sh
          kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
      - name: Template values.yaml
        run: |
          TAG=$(echo '${{ needs.upload_images.outputs.container-image }}' | sed 's|.*:||')
          sed -i "s|%TROW_IMAGE_TAG%|${TAG}|" .github/workflows/config/values.yaml
      - name: Helm Install Trow
        run: |
          helm install trow-test -f .github/workflows/config/values.yaml charts/trow/
      - name: Pull and Tag Docker Image
        run: |
          docker pull nginx:alpine
          docker tag nginx:alpine 127.0.0.1/test/nginx:alpine
      - name: Push to Trow
        run: |
          kubectl wait pod/trow-test-0 --for condition=ready --timeout=300s
          docker push  127.0.0.1/test/nginx:alpine
