name: Helm Chart

on:
  push:
    branches:
    - "*"

jobs:
  helm_chart_validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
          version: v3.4.0

    - uses: actions/setup-python@v2
      with:
          python-version: 3.7

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
          config: ./ci-config/kind.yaml

    - name: Install Ingress
      run: |
          ./ci-config/install-kind-ingress.sh
          kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
    - name: Helm Install Trow
      run: |
        helm install trow-test -f ci-config/values.yaml charts/trow/
    - name: Pull and Tag Docker Image
      run: |
        docker pull nginx:alpine
        docker tag nginx:alpine trow.test/test/nginx:alpine
    - name: Push to Trow
      run: |
        kubectl wait pod/trow-test-0 --for condition=ready --timeout=300s
        docker push  127.0.0.1/test/nginx:alpine
