# Also builds the Docker images, but we want this name on the badge
name: OCI Conformance

on:
  push:
    branches:
      - main

jobs:
  upload_images:
    outputs:
      container-image: ${{ steps.build-images.outputs.container-image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - uses: sigstore/cosign-installer@main
      - name: Build and push multi-arch image
        id: build-images
        run: ./docker/multi-arch.sh
        env:
          COSIGN_EXPERIMENTAL: 1
