name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        default: true
        components: rustfmt
    - name: Run Cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose --workspace
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
    - name: Run trow-server test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -p trow-server --verbose
    - name: Run Trow test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -p trow --verbose
    - name: Smoke test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --ignored
